In [1]:
import sklearn

In [2]:
sklearn.__version__

'1.2.1'

In [18]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.metrics import accuracy_score

In [6]:
print(load_iris().DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [7]:
iris = load_iris()

In [8]:
type(iris)

sklearn.utils._bunch.Bunch

In [9]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [10]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [11]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [14]:
iris_df = pd.DataFrame(data=iris.data,
             columns=iris.feature_names)

In [15]:
iris_df['label'] = iris.target
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [17]:
x_train,x_test,y_train,y_test = train_test_split(iris.data,
                                 iris.target,
                                 test_size=0.2,
                                 random_state=11)

In [19]:
dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf.fit(x_train,y_train)
pred = dt_clf.predict(x_test)
accuracy_score(y_test,pred)

0.9333333333333333

In [20]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [21]:
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [22]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [23]:
dt_clf = DecisionTreeClassifier()
dt_clf.fit(iris.data,iris.target)
pred = dt_clf.predict(iris.data)
accuracy_score(iris.target,pred)

1.0

In [34]:
x_train,x_test,y_train,y_test = train_test_split(iris.data,
                                 iris.target,
                                 test_size=0.3,
                                 random_state=None)

In [35]:
dt_clf = DecisionTreeClassifier(random_state=None)
dt_clf.fit(x_train,y_train)
pred = dt_clf.predict(x_test)
accuracy_score(y_test,pred)

0.9111111111111111

In [36]:
#KFold

In [37]:
from sklearn.model_selection import KFold
import numpy as np

In [38]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

In [52]:
kfold = KFold(n_splits=5,shuffle=True)
cv_accuracy = []
print(iris.data.shape)

(150, 4)


In [53]:
n_iter = 0
for train_index,test_index in kfold.split(iris.data):
    # print(train_index)
    # print(test_index)
    x_train,x_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    # print(x_test)
    dt_clf.fit(x_train,y_train)
    pred = dt_clf.predict(x_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    print(f'{n_iter} 교차 검증 정확도 :{accuracy}, 학습데이터 크기:{train_size}, 검증데이터 크기:{test_size}')
    print(f'검증데이터 인덱스:{test_index}')
    cv_accuracy.append(accuracy)
print(f'평균 정확도:{np.mean(cv_accuracy)}')

1 교차 검증 정확도 :0.9667, 학습데이터 크기:120, 검증데이터 크기:30
검증데이터 인덱스:[  4   6   8  13  15  18  22  28  29  32  33  38  47  68  71  74  75  78
  84 111 116 125 128 130 134 137 138 141 142 149]
2 교차 검증 정확도 :0.9333, 학습데이터 크기:120, 검증데이터 크기:30
검증데이터 인덱스:[  1   2   7  11  16  20  21  34  40  42  43  48  50  51  56  58  59  65
  77  79  83  91  94  98 101 102 117 118 120 129]
3 교차 검증 정확도 :1.0, 학습데이터 크기:120, 검증데이터 크기:30
검증데이터 인덱스:[  0   9  10  12  14  23  30  35  36  39  45  53  63  64  67  69  73  76
  90  92  93  95 103 114 123 135 136 139 143 145]
4 교차 검증 정확도 :0.9333, 학습데이터 크기:120, 검증데이터 크기:30
검증데이터 인덱스:[ 17  19  24  27  31  41  44  49  52  54  60  70  72  80  97  99 104 105
 107 108 109 112 113 115 119 122 126 127 131 147]
5 교차 검증 정확도 :0.9333, 학습데이터 크기:120, 검증데이터 크기:30
검증데이터 인덱스:[  3   5  25  26  37  46  55  57  61  62  66  81  82  85  86  87  88  89
  96 100 106 110 121 124 132 133 140 144 146 148]
평균 정확도:0.9533200000000001


In [56]:
kfold = KFold(n_splits=3,shuffle=True)
n_iter = 0
for train_index,test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(f'{n_iter} 교차검증')
    print(f'학습 레이블 데이터 분포:\n{label_train.value_counts()}')
    print(f'검증 레이블 데이터 분포:\n{label_test.value_counts()}')

1 교차검증
학습 레이블 데이터 분포:
0    36
2    34
1    30
Name: label, dtype: int64
검증 레이블 데이터 분포:
1    20
2    16
0    14
Name: label, dtype: int64
2 교차검증
학습 레이블 데이터 분포:
2    36
0    34
1    30
Name: label, dtype: int64
검증 레이블 데이터 분포:
1    20
0    16
2    14
Name: label, dtype: int64
3 교차검증
학습 레이블 데이터 분포:
1    40
0    30
2    30
Name: label, dtype: int64
검증 레이블 데이터 분포:
0    20
2    20
1    10
Name: label, dtype: int64


In [57]:
from sklearn.model_selection import StratifiedKFold

In [59]:
skfold = StratifiedKFold(n_splits=3,shuffle=False)
n_iter = 0
for train_index,test_index in skfold.split(iris_df,iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(f'{n_iter} 교차검증')
    print(f'학습 레이블 데이터 분포:\n{label_train.value_counts()}')
    print(f'검증 레이블 데이터 분포:\n{label_test.value_counts()}')

1 교차검증
학습 레이블 데이터 분포:
2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
0    17
1    17
2    16
Name: label, dtype: int64
2 교차검증
학습 레이블 데이터 분포:
1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
0    17
2    17
1    16
Name: label, dtype: int64
3 교차검증
학습 레이블 데이터 분포:
0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
1    17
2    17
0    16
Name: label, dtype: int64


In [60]:
skfold = StratifiedKFold(n_splits=3,shuffle=False)
n_iter = 0
for train_index,test_index in skfold.split(iris.data,iris.target):
    # print(train_index)
    # print(test_index)
    x_train,x_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    # print(x_test)
    dt_clf.fit(x_train,y_train)
    pred = dt_clf.predict(x_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    print(f'{n_iter} 교차 검증 정확도 :{accuracy}, 학습데이터 크기:{train_size}, 검증데이터 크기:{test_size}')
    print(f'검증데이터 인덱스:{test_index}')
    cv_accuracy.append(accuracy)
print(f'평균 정확도:{np.mean(cv_accuracy)}')

1 교차 검증 정확도 :0.98, 학습데이터 크기:100, 검증데이터 크기:50
검증데이터 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
2 교차 검증 정확도 :0.94, 학습데이터 크기:100, 검증데이터 크기:50
검증데이터 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
3 교차 검증 정확도 :0.98, 학습데이터 크기:100, 검증데이터 크기:50
검증데이터 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]
평균 정확도:0.958325
