In [2]:
import sklearn

In [3]:
sklearn.__version__

'1.2.1'

In [4]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn.metrics import accuracy_score

In [5]:
print(load_iris().DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [6]:
iris = load_iris()

In [7]:
type(iris)

sklearn.utils._bunch.Bunch

In [8]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [9]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [10]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
iris_df = pd.DataFrame(data=iris.data,
             columns=iris.feature_names)

In [12]:
iris_df['label'] = iris.target
iris_df.head(3)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [13]:
x_train,x_test,y_train,y_test = train_test_split(iris.data,
                                 iris.target,
                                 test_size=0.2,
                                 random_state=11)

In [14]:
dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf.fit(x_train,y_train)
pred = dt_clf.predict(x_test)
accuracy_score(y_test,pred)

0.9333333333333333

In [15]:
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [16]:
y_test

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [17]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [18]:
dt_clf = DecisionTreeClassifier()
dt_clf.fit(iris.data,iris.target)
pred = dt_clf.predict(iris.data)
accuracy_score(iris.target,pred)

1.0

In [19]:
x_train,x_test,y_train,y_test = train_test_split(iris.data,
                                 iris.target,
                                 test_size=0.3,
                                 random_state=None)

In [20]:
dt_clf = DecisionTreeClassifier(random_state=None)
dt_clf.fit(x_train,y_train)
pred = dt_clf.predict(x_test)
accuracy_score(y_test,pred)

0.9555555555555556

In [21]:
#KFold

In [22]:
from sklearn.model_selection import KFold
import numpy as np

In [23]:
iris = load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

In [24]:
kfold = KFold(n_splits=5,shuffle=True)
cv_accuracy = []
print(iris.data.shape)

(150, 4)


In [25]:
n_iter = 0
for train_index,test_index in kfold.split(iris.data):
    # print(train_index)
    # print(test_index)
    x_train,x_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    # print(x_test)
    dt_clf.fit(x_train,y_train)
    pred = dt_clf.predict(x_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    print(f'{n_iter} 교차 검증 정확도 :{accuracy}, 학습데이터 크기:{train_size}, 검증데이터 크기:{test_size}')
    print(f'검증데이터 인덱스:{test_index}')
    cv_accuracy.append(accuracy)
print(f'평균 정확도:{np.mean(cv_accuracy)}')

1 교차 검증 정확도 :0.9333, 학습데이터 크기:120, 검증데이터 크기:30
검증데이터 인덱스:[  8  11  12  18  21  24  28  36  37  43  48  50  56  63  74  87  89  92
  97 104 106 112 117 123 129 130 135 145 147 149]
2 교차 검증 정확도 :0.9333, 학습데이터 크기:120, 검증데이터 크기:30
검증데이터 인덱스:[  3   4  14  15  22  23  30  35  38  39  42  57  60  62  65  69  71  72
  75  80  85  94  96 100 115 118 119 136 138 141]
3 교차 검증 정확도 :0.9667, 학습데이터 크기:120, 검증데이터 크기:30
검증데이터 인덱스:[  2   7  19  31  45  51  52  54  55  58  66  78  84  95 103 107 108 109
 111 113 114 116 121 125 127 128 131 132 133 148]
4 교차 검증 정확도 :0.9, 학습데이터 크기:120, 검증데이터 크기:30
검증데이터 인덱스:[  0   1   6   9  16  17  20  25  33  40  44  46  59  64  68  70  73  77
  81  83  86  90  93 101 102 120 122 134 137 144]
5 교차 검증 정확도 :1.0, 학습데이터 크기:120, 검증데이터 크기:30
검증데이터 인덱스:[  5  10  13  26  27  29  32  34  41  47  49  53  61  67  76  79  82  88
  91  98  99 105 110 124 126 139 140 142 143 146]
평균 정확도:0.94666


In [26]:
kfold = KFold(n_splits=3,shuffle=True)
n_iter = 0
for train_index,test_index in kfold.split(iris_df):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(f'{n_iter} 교차검증')
    print(f'학습 레이블 데이터 분포:\n{label_train.value_counts()}')
    print(f'검증 레이블 데이터 분포:\n{label_test.value_counts()}')

1 교차검증
학습 레이블 데이터 분포:
2    35
0    33
1    32
Name: label, dtype: int64
검증 레이블 데이터 분포:
1    18
0    17
2    15
Name: label, dtype: int64
2 교차검증
학습 레이블 데이터 분포:
2    35
0    33
1    32
Name: label, dtype: int64
검증 레이블 데이터 분포:
1    18
0    17
2    15
Name: label, dtype: int64
3 교차검증
학습 레이블 데이터 분포:
1    36
0    34
2    30
Name: label, dtype: int64
검증 레이블 데이터 분포:
2    20
0    16
1    14
Name: label, dtype: int64


In [27]:
from sklearn.model_selection import StratifiedKFold

In [28]:
skfold = StratifiedKFold(n_splits=3,shuffle=False)
n_iter = 0
for train_index,test_index in skfold.split(iris_df,iris_df['label']):
    n_iter += 1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(f'{n_iter} 교차검증')
    print(f'학습 레이블 데이터 분포:\n{label_train.value_counts()}')
    print(f'검증 레이블 데이터 분포:\n{label_test.value_counts()}')

1 교차검증
학습 레이블 데이터 분포:
2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
0    17
1    17
2    16
Name: label, dtype: int64
2 교차검증
학습 레이블 데이터 분포:
1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
0    17
2    17
1    16
Name: label, dtype: int64
3 교차검증
학습 레이블 데이터 분포:
0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
1    17
2    17
0    16
Name: label, dtype: int64


In [29]:
skfold = StratifiedKFold(n_splits=3,shuffle=False)
n_iter = 0
cv_accuracy = []
for train_index,test_index in skfold.split(iris.data,iris.target):
    # print(train_index)
    # print(test_index)
    x_train,x_test = iris.data[train_index],iris.data[test_index]
    y_train,y_test = iris.target[train_index],iris.target[test_index]
    # print(x_test)
    dt_clf.fit(x_train,y_train)
    pred = dt_clf.predict(x_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = x_train.shape[0]
    test_size = x_test.shape[0]
    print(f'{n_iter} 교차 검증 정확도 :{accuracy}, 학습데이터 크기:{train_size}, 검증데이터 크기:{test_size}')
    print(f'검증데이터 인덱스:{test_index}')
    cv_accuracy.append(accuracy)
print(f'평균 정확도:{np.mean(cv_accuracy)}')

1 교차 검증 정확도 :0.98, 학습데이터 크기:100, 검증데이터 크기:50
검증데이터 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
2 교차 검증 정확도 :0.94, 학습데이터 크기:100, 검증데이터 크기:50
검증데이터 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
3 교차 검증 정확도 :0.98, 학습데이터 크기:100, 검증데이터 크기:50
검증데이터 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]
평균 정확도:0.9666666666666667


In [30]:
# 교차검증 cross_val_score()

In [31]:
from sklearn.model_selection import cross_val_score

In [37]:
dt_clf = DecisionTreeClassifier(random_state=156)
cross_val_score(dt_clf,
                iris.data,
                iris.target,
                cv=3,
                scoring='accuracy',
                verbose=0)

array([0.98, 0.94, 0.98])

In [39]:
from sklearn.model_selection import GridSearchCV

In [40]:
x_train,x_test,y_train,y_test = train_test_split(iris.data,
                                 iris.target,
                                 test_size=0.2,
                                 random_state=121)
dtree = DecisionTreeClassifier()
param = {'max_depth':[1,2,3],
         'min_samples_split':[2,3]}

In [41]:
grid_tree = GridSearchCV(dtree,
             param_grid=param,
             cv=3,
             refit=True)

In [42]:
grid_tree.fit(x_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': [1, 2, 3], 'min_samples_split': [2, 3]})

In [43]:
grid_tree.best_score_

0.975

In [44]:
grid_tree.best_params_

{'max_depth': 3, 'min_samples_split': 2}

In [45]:
grid_tree.best_index_

4

In [48]:
df = pd.DataFrame(grid_tree.cv_results_)

In [49]:
df.columns

Index(['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time',
       'param_max_depth', 'param_min_samples_split', 'params',
       'split0_test_score', 'split1_test_score', 'split2_test_score',
       'mean_test_score', 'std_test_score', 'rank_test_score'],
      dtype='object')

In [51]:
df[['params',
    'mean_test_score',
    'rank_test_score',
    'split0_test_score', 
    'split1_test_score', 
    'split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [52]:
pred = grid_tree.predict(x_test)

In [53]:
accuracy_score(y_test,pred)

0.9666666666666667

In [54]:
pred = grid_tree.best_estimator_.predict(x_test)
accuracy_score(y_test,pred)

0.9666666666666667