In [7]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [8]:
items=['TV','냉장고','전자레인지','컴퓨터','선풍기','믹서','믹서',np.nan]

In [9]:
encoder = LabelEncoder()
# encoder.fit(items)
# labels = encoder.transform(items)
labels = encoder.fit_transform(items)
labels

array([0, 2, 5, 6, 4, 3, 3, 1])

In [10]:
encoder.classes_

array(['TV', 'nan', '냉장고', '믹서', '선풍기', '전자레인지', '컴퓨터'], dtype='<U32')

In [11]:
encoder.inverse_transform([2,4,1,3,6])

array(['냉장고', '선풍기', 'nan', '믹서', '컴퓨터'], dtype='<U32')

In [12]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']
items = np.array(items).reshape(-1,1)
items.shape

(7, 1)

In [18]:
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [19]:
import pandas as pd

In [24]:
items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']
pd.get_dummies(items).values

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]], dtype=uint8)